# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a936241e27f338f1372980831f25e7d244c9ff7a19e2a3eb5611a66f5232d83e4295f6adda1cad5a07507d40e26820b8a8c543bdcef52fbb453107d67af746f

test:
  secret_key_base: 97a3cb47fbcbb449162c15c1118cbf51a896130537ec3c494ff50aeaee68df1eb915d30a3977d52eb1995477fe3f68af1fb25a02e39c7012042c0942a5a7a753

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
